Repository gojue/ecaptureQ, pull requests merged in 2025-08, with the labels that each got.

#1 feat: Update project name and descriptions for eCaptureQ
  app-icon.png
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/icons/128x128.png
  src-tauri/icons/128x128@2x.png
  src-tauri/icons/32x32.png
  src-tauri/icons/64x64.png
  src-tauri/icons/Square107x107Logo.png
  src-tauri/icons/Square142x142Logo.png
  src-tauri/icons/Square150x150Logo.png
  src-tauri/icons/Square284x284Logo.png
  src-tauri/icons/Square30x30Logo.png
  src-tauri/icons/Square310x310Logo.png
  src-tauri/icons/Square44x44Logo.png
  src-tauri/icons/Square71x71Logo.png
  src-tauri/icons/Square89x89Logo.png
  src-tauri/icons/StoreLogo.png
  src-tauri/icons/icon.icns
  src-tauri/icons/icon.ico
  src-tauri/icons/icon.png
  src-tauri/icons/ios/AppIcon-20x20@1x.png
  src-tauri/icons/ios/AppIcon-20x20@2x-1.png
  src-tauri/icons/ios/AppIcon-20x20@2x.png
  src-tauri/icons/ios/AppIcon-20x20@3x.png
  src-tauri/icons/ios/AppIcon-29x29@1x.png
  src-tauri/icons/ios/AppIcon-29x29@2x-1.png
  src-tauri/icons/ios/AppIcon-29x29@2x.png
  src-tauri/icons/ios/AppIcon-29x29@3x.png
  src-tauri/icons/ios/AppIcon-40x40@1x.png
  src-tauri/icons/ios/AppIcon-40x40@2x-1.png
  src-tauri/icons/ios/AppIcon-40x40@2x.png
  src-tauri/icons/ios/AppIcon-40x40@3x.png
  src-tauri/icons/ios/AppIcon-512@2x.png
  src-tauri/icons/ios/AppIcon-60x60@2x.png
  src-tauri/icons/ios/AppIcon-60x60@3x.png
  src-tauri/icons/ios/AppIcon-76x76@1x.png
  src-tauri/icons/ios/AppIcon-76x76@2x.png
  src-tauri/icons/ios/AppIcon-83.5x83.5@2x.png
  src-tauri/src/lib.rs
  src-tauri/src/services/capture.rs
  src-tauri/src/tauri_bridge/commands.rs
  src-tauri/tauri.conf.json
Labels: documentation

#2 feat: Add GitHub Actions workflow for PR builds and artifact uploads
  .github/workflows/pr-build.yml
  .github/workflows/pr_build_android.yml
  package.json
  scripts/log.sh
  src-tauri/src/lib.rs
  src-tauri/src/services/capture.rs
  src-tauri/src/services/push_service.rs
  src-tauri/src/services/websocket.rs
  src-tauri/src/tauri_bridge/commands.rs
  src-tauri/tauri.conf.json
  src/pages/SettingsPage.tsx
Labels: documentation, enhancement

#5 chore: remove native-tls feature
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
Labels: enhancement

#7 feat: Update CI workflows for eCapture; generalize artifact naming and add new release workflow
  .github/workflows/pr-build.yml
  .github/workflows/pr_build_android.yml
  .github/workflows/release.yml
  package.json
  src-tauri/Cargo.toml
  src-tauri/src/lib.rs
  src-tauri/src/services/capture.rs
  src-tauri/tauri.conf.json
Labels: enhancement
